<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pageman</string>
	</array>
	<key>name</key>
	<string>Pageman</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.html-comment.pageman</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;(?:[^&gt;\\]|\\.)*</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>string.html-tag.pageman</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>```</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>variable.other.muliline-markdown-pre-box.pageman</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\|</string>
			<key>end</key>
			<string>\|\s*$</string>
			<key>name</key>
			<string>storage.type.markdown-table.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string> \&amp;[a-zA-Z0-9]+\;</string>
			<key>name</key>
			<string>variable.other.html-special-chars.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`(?:[^`\\]|\\.)+`</string>
			<key>name</key>
			<string>variable.other.inline-code-block-markdown.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(&gt;|-|[0-9]+\.)\s</string>
			<key>name</key>
			<string>keyword.numeric.lists-markdown.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!?\[(?:[^\]\\]|\\.)*\]\((?:[^\)\\]|\\.)*\)</string>
			<key>name</key>
			<string>keyword.control.markdown-image-or-link.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(_\*\*(?:[^(\*\*_)\\]|\\.)*\*\*_|\*\*_(?:[^(_\*\*)\\]|\\.)*_\*\*|\*\*\*(?:[^(\*\*\*)\\]|\\.)*\*\*\*)</string>
			<key>name</key>
			<string>markup.italic.bold.bold-and-italic-markdown.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_(?:[^(_)\\]|\\.)*_</string>
			<key>name</key>
			<string>markup.italic.markdown-italic.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*(?:[^(\*)\\]|\\.)+\*</string>
			<key>name</key>
			<string>markup.italic.markdow-italic.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*(?:[^(\*\*)\\]|\\.)+\*\*</string>
			<key>name</key>
			<string>markup.bold.makrdown-bold.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*//.*$</string>
			<key>name</key>
			<string>comment.double-slash.c-comments.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^(?:[^\^\\]|\\.)*\^</string>
			<key>name</key>
			<string>storage.type.legend.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#+.*$</string>
			<key>name</key>
			<string>variable.other.markdown-header.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*---.*$</string>
			<key>name</key>
			<string>constant.language.pageman-parts.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z]+\s*\:(?:[^\:\\]|\\.)*$</string>
			<key>name</key>
			<string>constant.language.jekyll-header.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{%(?:[^%\}\\]|\\.)*%\}</string>
			<key>name</key>
			<string>storage.type.liquid-g1.pageman</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{\{(?:[^\}\}\\]|\\.)*\}\}</string>
			<key>name</key>
			<string>storage.type.liquid-g2.pageman</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.pageman</string>
	<key>uuid</key>
	<string>d2c2ca1c-8188-4647-aec8-758714a59cea</string>
</dict>
</plist>
